[tool.poetry]
package-mode = false
name = "rag-chatbot"
version = "0.1.0"
description = "Retrieval Augmented Generation application with Gradio frontend"
authors = [
    "Aleksey Strylchuk <none>"
]


[tool.poetry.dependencies]
python = "^3.10"
gradio = "<5.0"
python-dotenv = "^1.0.1"
pydantic = "^2.6.4"
llama-index-embeddings-ollama = "0.7.0"
llama-index-vector-stores-chroma = "0.5.0"
llama-index-llms-ollama = "0.7.0"
llama-index-readers-file = "0.5.0"
llama-index = "0.13.0"
transformers = "^4.39.1"
llama-index-callbacks-wandb = "0.4.0"
llama-index-retrievers-bm25 = "0.6.1"
pymupdf = "^1.24.3"
tqdm = "^4.66.4"
requests = "^2.32.3"
pandas = "^2.2.3"
sentence-transformers = "^3.2.0"
debugpy = "1.8.15"
unstructured = {version = "0.18.11", extras = ["csv", "doc", "docx", "xlsx"]}


[tool.poetry.group.dev.dependencies]
ruff = "^0.6.9"
deptry = "^0.20.0"
pytest = "^8.3.3"


[tool.deptry.per_rule_ignores]
DEP002 = ["sentence-transformers"]


# [build-system]
# requires = ["poetry-core"]
# build-backend = "poetry.core.masonry.api"
